package com.demospace.servicedemo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class customer implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Customer Id")
	private java.lang.String custId;
	@org.kie.api.definition.type.Label("Name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label("Phone")
	private java.lang.String phone;
	@org.kie.api.definition.type.Label("Email")
	private java.lang.String email;
	@org.kie.api.definition.type.Label("Date of Birth")
	private String dob;

	@org.kie.api.definition.type.Label("Credit Score")
	private java.lang.Integer creditScore;

	@org.kie.api.definition.type.Label("Services")
	private service services;

	@org.kie.api.definition.type.Label("Existing Services")
	private java.util.List<com.demospace.servicedemo.service> existingServices;

	public customer() {
	}

	public java.lang.String getCustId() {
		return this.custId;
	}

	public void setCustId(java.lang.String custId) {
		this.custId = custId;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getPhone() {
		return this.phone;
	}

	public void setPhone(java.lang.String phone) {
		this.phone = phone;
	}

	public java.lang.String getEmail() {
		return this.email;
	}

	public void setEmail(java.lang.String email) {
		this.email = email;
	}

	public java.lang.Integer getCreditScore() {
		return this.creditScore;
	}

	public void setCreditScore(java.lang.Integer creditScore) {
		this.creditScore = creditScore;
	}

	public java.lang.String getDob() {
		return this.dob;
	}

	public void setDob(java.lang.String dob) {
		this.dob = dob;
	}

	public com.demospace.servicedemo.service getServices() {
		return this.services;
	}

	public void setServices(com.demospace.servicedemo.service services) {
		this.services = services;
	}

	public java.util.List<com.demospace.servicedemo.service> getExistingServices() {
		return this.existingServices;
	}

	public void setExistingServices(
			java.util.List<com.demospace.servicedemo.service> existingServices) {
		this.existingServices = existingServices;
	}

	public customer(java.lang.String custId, java.lang.String name,
			java.lang.String phone, java.lang.String email,
			java.lang.String dob, java.lang.Integer creditScore,
			com.demospace.servicedemo.service services,
			java.util.List<com.demospace.servicedemo.service> existingServices) {
		this.custId = custId;
		this.name = name;
		this.phone = phone;
		this.email = email;
		this.dob = dob;
		this.creditScore = creditScore;
		this.services = services;
		this.existingServices = existingServices;
	}

}