package com.demospace.servicedemo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class offer implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Id")
	private java.lang.String id;
	@org.kie.api.definition.type.Label("Type")
	private java.lang.String type;
	@org.kie.api.definition.type.Label("Name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label("Description")
	private java.lang.String description;
	@org.kie.api.definition.type.Label("Discount")
	private java.lang.Integer discount;

	@org.kie.api.definition.type.Label(value = "Select an Offer")
	private java.lang.Boolean selectOffer;

	public offer() {
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public java.lang.Integer getDiscount() {
		return this.discount;
	}

	public void setDiscount(java.lang.Integer discount) {
		this.discount = discount;
	}

	public java.lang.Boolean getSelectOffer() {
		return this.selectOffer;
	}

	public void setSelectOffer(java.lang.Boolean selectOffer) {
		this.selectOffer = selectOffer;
	}

	public offer(java.lang.String id, java.lang.String type,
			java.lang.String name, java.lang.String description,
			java.lang.Integer discount, java.lang.Boolean selectOffer) {
		this.id = id;
		this.type = type;
		this.name = name;
		this.description = description;
		this.discount = discount;
		this.selectOffer = selectOffer;
	}

}