package com.demospace.servicedemo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class serviceRequest implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Service Id")
	private java.lang.String sevID;
	@org.kie.api.definition.type.Label("Customer Id")
	private java.lang.String custId;
	@org.kie.api.definition.type.Label("Credit Approved")
	private java.lang.Boolean creditApproved;
	@org.kie.api.definition.type.Label("Is Contract Active")
	private java.lang.Boolean contractActive;
	@org.kie.api.definition.type.Label("Account Balance")
	private java.lang.Double accBal;

	@org.kie.api.definition.type.Label("Initial Down Payment")
	private java.lang.Double initalPayment;

	@org.kie.api.definition.type.Label("Request Type")
	private java.lang.String type;

	@org.kie.api.definition.type.Label("Customer Offers")
	private java.util.List<com.demospace.servicedemo.offer> custOffers;

	public serviceRequest() {
	}

	public java.lang.String getSevID() {
		return this.sevID;
	}

	public void setSevID(java.lang.String sevID) {
		this.sevID = sevID;
	}

	public java.lang.String getCustId() {
		return this.custId;
	}

	public void setCustId(java.lang.String custId) {
		this.custId = custId;
	}

	public java.lang.Boolean getCreditApproved() {
		return this.creditApproved;
	}

	public void setCreditApproved(java.lang.Boolean creditApproved) {
		this.creditApproved = creditApproved;
	}

	public java.lang.Boolean getContractActive() {
		return this.contractActive;
	}

	public void setContractActive(java.lang.Boolean contractActive) {
		this.contractActive = contractActive;
	}

	public java.lang.Double getAccBal() {
		return this.accBal;
	}

	public void setAccBal(java.lang.Double accBal) {
		this.accBal = accBal;
	}

	public java.lang.Double getInitalPayment() {
		return this.initalPayment;
	}

	public void setInitalPayment(java.lang.Double initalPayment) {
		this.initalPayment = initalPayment;
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public java.util.List<com.demospace.servicedemo.offer> getCustOffers() {
		return this.custOffers;
	}

	public void setCustOffers(
			java.util.List<com.demospace.servicedemo.offer> custOffers) {
		this.custOffers = custOffers;
	}

	public serviceRequest(java.lang.String sevID, java.lang.String custId,
			java.lang.Boolean creditApproved, java.lang.Boolean contractActive,
			java.lang.Double accBal, java.lang.Double initalPayment,
			java.lang.String type,
			java.util.List<com.demospace.servicedemo.offer> custOffers) {
		this.sevID = sevID;
		this.custId = custId;
		this.creditApproved = creditApproved;
		this.contractActive = contractActive;
		this.accBal = accBal;
		this.initalPayment = initalPayment;
		this.type = type;
		this.custOffers = custOffers;
	}

}