package com.demospace.servicedemo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class service implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Type")
	private java.lang.String type;
	@org.kie.api.definition.type.Label("Name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label("Description")
	private java.lang.String description;
	@org.kie.api.definition.type.Label("Id")
	private java.lang.String id;
	@org.kie.api.definition.type.Label("End Date")
	private java.lang.String endDate;
	@org.kie.api.definition.type.Label("Start Date")
	private java.lang.String startDate;
	@org.kie.api.definition.type.Label("Monthly Payment")
	private java.lang.Double monthlyPay;

	@org.kie.api.definition.type.Label("Select Service")
	private boolean selService;

	public service() {
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.lang.String getEndDate() {
		return this.endDate;
	}

	public void setEndDate(java.lang.String endDate) {
		this.endDate = endDate;
	}

	public java.lang.String getStartDate() {
		return this.startDate;
	}

	public void setStartDate(java.lang.String startDate) {
		this.startDate = startDate;
	}

	public java.lang.Double getMonthlyPay() {
		return this.monthlyPay;
	}

	public void setMonthlyPay(java.lang.Double monthlyPay) {
		this.monthlyPay = monthlyPay;
	}

	public boolean getSelService() {
		return this.selService;
	}

	public void setSelService(boolean selService) {
		this.selService = selService;
	}

	public service(java.lang.String type, java.lang.String name,
			java.lang.String description, java.lang.String id,
			java.lang.String endDate, java.lang.String startDate,
			java.lang.Double monthlyPay, boolean selService) {
		this.type = type;
		this.name = name;
		this.description = description;
		this.id = id;
		this.endDate = endDate;
		this.startDate = startDate;
		this.monthlyPay = monthlyPay;
		this.selService = selService;
	}

}